# Generated by Django 5.2.8 on 2025-12-14 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('mug', 'Personalized Mug'), ('tshirt', 'Custom T-Shirt'), ('canvas', 'Photo Canvas'), ('pillow', 'Decorative Pillow'), ('blanket', 'Photo Blanket')], max_length=20)),
                ('custom_text', models.CharField(blank=True, max_length=50)),
                ('text_color', models.CharField(default='#000000', max_length=20)),
                ('text_font', models.CharField(max_length=50)),
                ('packaging', models.CharField(max_length=20)),
                ('gift_wrap', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='custom_uploads/')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
